plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-yard

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - "spec/integration/**/*"

RSpec/InstanceVariable:
  Exclude:
    - "spec/integration/**/*"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
