name: Quality checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint with RuboCop
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          show-progress: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

  unit-test:
    name: Unit tests with RSpec
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec

  docs-build:
    name: YARD documentation build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          show-progress: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1
        with:
          ruby-version: "4.0"
          bundler-cache: true

      - name: Build YARD documentation
        run: bundle exec rake yard
