name: Quality checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint with RuboCop
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          show-progress: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

  unit-test:
    name: Unit tests with RSpec
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec

  docs-build:
    name: YARD documentation build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          show-progress: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1
        with:
          ruby-version: "4.0"
          bundler-cache: true

      - name: Build YARD documentation
        run: bundle exec rake yard
